spring.application.name=usuario_service
server.port=8082

spring.profiles.active=dev

# Documentacion OpenAPI / Swagger UI -> http://localhost:8082/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html
