spring.application.name=cita_service
server.port=8085

spring.profiles.active=dev

# URLs de los microservicios que consulta (comunicacion via WebClient)
services.mascota.url=http://localhost:8084
services.usuario.url=http://localhost:8082

# Documentacion OpenAPI / Swagger UI -> http://localhost:8085/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html
