spring.application.name=mascota_service
server.port=8084

spring.profiles.active=dev

# URL del microservicio cliente_service (comunicacion via WebClient)
services.cliente.url=http://localhost:8083

# Documentacion OpenAPI / Swagger UI -> http://localhost:8084/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ====== Seguridad JWT (valida el token emitido por auth_service) ======
jwt.secret=122345678912345678912345678912345
app.security.write-roles=ADMIN,VETERINARIO,RECEPCIONISTA
