spring.application.name=historial_service
server.port=8086

spring.profiles.active=dev

# URL del microservicio mascota_service (comunicacion via WebClient)
services.mascota.url=http://localhost:8084

# Documentacion OpenAPI / Swagger UI -> http://localhost:8086/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# ====== Seguridad JWT (valida el token emitido por auth_service) ======
jwt.secret=122345678912345678912345678912345
app.security.write-roles=ADMIN,VETERINARIO
