spring.application.name=auth_service
server.port=8081

spring.profiles.active=dev

# JWT
jwt.secret=122345678912345678912345678912345
jwt.expiration=14400000

# Documentacion OpenAPI / Swagger UI -> http://localhost:8081/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html
