spring.application.name=auth_service
spring.profiles.active=dev

server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

jwt.secret=122345678912345678912345678912345
jwt.expiration=14400000