spring.application.name=auth_service
server.port=8081
spring.profiles.active=dev

# Mapeo de variables de entorno (Docker Compose)
usuario.service.url=${USUARIO_URL:http://localhost:8082}
service-account.username=${SERVICE_ACCOUNT_USERNAME:sistema-interno}
service-account.password=${SERVICE_ACCOUNT_PASSWORD:ClaveSegura123!}

# JWT
jwt.secret=122345678912345678912345678912345
jwt.expiration=14400000

# Documentacion OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html